apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxmox-mock
  namespace: proxmox-mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxmox-mock
  template:
    metadata:
      labels:
        app: proxmox-mock
    spec:
      containers:
        - name: proxmox-mock
          image: proxmox-mock:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 22
          env:
            - name: AUTHORIZED_KEYS
              value: ""
