apiVersion: v1
kind: Service
metadata:
  name: proxmox-mock-ssh
  namespace: proxmox-mock
spec:
  selector:
    app: proxmox-mock
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
